"""Behavioral contracts shared by local and PostgreSQL repositories."""

from __future__ import annotations

from typing import Any, Protocol


class InboxRepository(Protocol):
    def append_once(self, record: Any) -> bool: ...
    def list_space_ids(self) -> list[str]: ...
    def load(self, space_id: str) -> list[dict[str, Any]]: ...
    def load_pending(self, space_id: str) -> list[dict[str, Any]]: ...
    def mark_processed(self, space_id: str, record_id: str) -> None: ...


class TaskRepository(Protocol):
    def create(self, task: dict[str, Any]) -> bool: ...
    def get(self, task_id: str) -> dict[str, Any] | None: ...
    def update_status(self, task_id: str, status: str, **updates: Any) -> None: ...


class NoteRepository(Protocol):
    def save(self, note: Any) -> bool: ...
    def list(self, space_id: str) -> list[dict[str, Any]]: ...
    def find(self, space_id: str, note_id: str) -> dict[str, Any] | None: ...
    def update(self, space_id: str, note_id: str, **updates: Any) -> dict[str, Any] | None: ...


class VectorRepository(Protocol):
    def add(self, space_id: str, item: Any) -> bool: ...
    def list(self, space_id: str) -> list[Any]: ...
    def remove(self, space_id: str, note_id: str) -> bool: ...


class MemoryRepository(Protocol):
    def get(self, memory_id: str) -> Any | None: ...
    def list(self, space_id: str, **filters: Any) -> list[Any]: ...
    def insert(self, space_id: str, candidate: Any, *, source_note_id: str, **options: Any) -> Any: ...


class DeliveryRepository(Protocol):
    def reserve(self, delivery_key: str, **values: Any) -> Any | None: ...
    def get(self, delivery_key: str) -> Any | None: ...
    def update_status(self, delivery_key: str, status: str, error: str | None = None) -> None: ...


class SummaryRepository(Protocol):
    def get(self, space_id: str) -> Any | None: ...
    def list_enabled(self) -> list[Any]: ...
    def upsert(self, subscription: Any) -> Any: ...
