"""Central runtime settings for Suixinji."""

from __future__ import annotations

import os

from dotenv import load_dotenv


load_dotenv()


def _int_env(name: str, default: int) -> int:
    value = os.getenv(name)
    if value is None or not value.strip():
        return default
    return int(value)


def _float_env(name: str, default: float) -> float:
    value = os.getenv(name)
    if value is None or not value.strip():
        return default
    return float(value)


def _bool_env(name: str, default: bool) -> bool:
    value = os.getenv(name)
    if value is None or not value.strip():
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


MAX_WORKERS = _int_env("SUIXINJI_MAX_WORKERS", 4)
TASK_QUEUE_SIZE = _int_env("SUIXINJI_TASK_QUEUE_SIZE", 100)
TASK_HISTORY_LIMIT = _int_env("SUIXINJI_TASK_HISTORY_LIMIT", 1000)
TASK_HISTORY_TTL_HOURS = _int_env("SUIXINJI_TASK_HISTORY_TTL_HOURS", 24)
PENDING_DRAIN_INTERVAL_SECONDS = _int_env("SUIXINJI_PENDING_DRAIN_INTERVAL_SECONDS", 15)
PENDING_DRAIN_BATCH_SIZE = _int_env("SUIXINJI_PENDING_DRAIN_BATCH_SIZE", 20)
DELIVERY_RESERVATION_TTL_SECONDS = _int_env("SUIXINJI_DELIVERY_RESERVATION_TTL_SECONDS", 600)
DELIVERY_MAX_ATTEMPTS = _int_env("SUIXINJI_DELIVERY_MAX_ATTEMPTS", 3)
LLM_TIMEOUT_SECONDS = _int_env("SUIXINJI_LLM_TIMEOUT_SECONDS", 15)
LLM_MAX_RETRIES = _int_env("SUIXINJI_LLM_MAX_RETRIES", 0)
EMBEDDING_TIMEOUT_SECONDS = _int_env("SUIXINJI_EMBEDDING_TIMEOUT_SECONDS", 10)
ENRICHMENT_MAX_WORKERS = _int_env("SUIXINJI_ENRICHMENT_MAX_WORKERS", 2)
ENRICHMENT_QUEUE_SIZE = _int_env("SUIXINJI_ENRICHMENT_QUEUE_SIZE", 50)
ENRICHMENT_DRAIN_INTERVAL_SECONDS = _int_env("SUIXINJI_ENRICHMENT_DRAIN_INTERVAL_SECONDS", 30)
ENRICHMENT_DRAIN_BATCH_SIZE = _int_env("SUIXINJI_ENRICHMENT_DRAIN_BATCH_SIZE", 20)
ENRICHMENT_MAX_ATTEMPTS = _int_env("SUIXINJI_ENRICHMENT_MAX_ATTEMPTS", 3)

RELATED_TOP_K = _int_env("SUIXINJI_RELATED_TOP_K", 3)
RELATED_MIN_SCORE = _float_env("SUIXINJI_RELATED_MIN_SCORE", 0.5)
QUERY_TOP_K = _int_env("SUIXINJI_QUERY_TOP_K", 5)
QUERY_MIN_SCORE = _float_env("SUIXINJI_QUERY_MIN_SCORE", 0.55)

MEMORY_DB_BUSY_TIMEOUT_MS = _int_env("SUIXINJI_MEMORY_DB_BUSY_TIMEOUT_MS", 10000)
MEMORY_DB_WRITE_MAX_ATTEMPTS = _int_env("SUIXINJI_MEMORY_DB_WRITE_MAX_ATTEMPTS", 3)
MEMORY_EXTRACTION_LEASE_SECONDS = _int_env("SUIXINJI_MEMORY_EXTRACTION_LEASE_SECONDS", 600)
MEMORY_CONSOLIDATION_RUN_LEASE_SECONDS = _int_env("SUIXINJI_MEMORY_CONSOLIDATION_RUN_LEASE_SECONDS", 600)
MEMORY_QUERY_MIN_SCORE = _float_env("SUIXINJI_MEMORY_QUERY_MIN_SCORE", 0.45)
MEMORY_EXTRACTOR_MODE = os.getenv("SUIXINJI_MEMORY_EXTRACTOR_MODE", "rules").strip().lower()
MEMORY_RETRIEVAL_MODE = os.getenv("SUIXINJI_MEMORY_RETRIEVAL_MODE", "hybrid").strip().lower()
MEMORY_CANDIDATE_MIN_CONFIDENCE = _float_env("SUIXINJI_MEMORY_CANDIDATE_MIN_CONFIDENCE", 0.45)
MEMORY_AUTO_MUTATION_MIN_CONFIDENCE = _float_env("SUIXINJI_MEMORY_AUTO_MUTATION_MIN_CONFIDENCE", 0.75)
MEMORY_ADJUDICATION_TOP_K = _int_env("SUIXINJI_MEMORY_ADJUDICATION_TOP_K", 8)
MEMORY_HYBRID_VECTOR_ENABLED = _bool_env("SUIXINJI_MEMORY_HYBRID_VECTOR_ENABLED", True)
MEMORY_HYBRID_RRF_K = _int_env("SUIXINJI_MEMORY_HYBRID_RRF_K", 60)

SUMMARY_DEFAULT_TIME = os.getenv("SUIXINJI_SUMMARY_DEFAULT_TIME", "22:00")

STORAGE_BACKEND = os.getenv("STORAGE_BACKEND", "local").strip().lower()
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
DATABASE_POOL_SIZE = _int_env("SUIXINJI_DATABASE_POOL_SIZE", 3)
DATABASE_MAX_OVERFLOW = _int_env("SUIXINJI_DATABASE_MAX_OVERFLOW", 2)
DATABASE_POOL_TIMEOUT_SECONDS = _int_env("SUIXINJI_DATABASE_POOL_TIMEOUT_SECONDS", 10)
DATABASE_POOL_RECYCLE_SECONDS = _int_env("SUIXINJI_DATABASE_POOL_RECYCLE_SECONDS", 1800)
DATABASE_GLOBAL_BUDGET = _int_env("SUIXINJI_DATABASE_GLOBAL_BUDGET", 40)
PROCESS_ROLE = os.getenv("SUIXINJI_PROCESS_ROLE", "default").strip().lower()


def database_pool_budget(role: str | None = None) -> tuple[int, int]:
    resolved = (role or PROCESS_ROLE or "default").lower()
    if resolved == "worker-heartbeat":
        return 1, 0
    if resolved == "receiver":
        return 1, 0
    if resolved == "outbox-relay":
        return 1, 0
    if resolved == "worker-adaptive":
        return 1, 1
    if resolved == "worker-ingest":
        return 3, 1
    if resolved.startswith("worker-") or resolved == "scheduler":
        return 1, 0
    return max(1, DATABASE_POOL_SIZE), max(0, DATABASE_MAX_OVERFLOW)

if STORAGE_BACKEND not in {"local", "postgres"}:
    raise ValueError("STORAGE_BACKEND must be 'local' or 'postgres'")
if STORAGE_BACKEND == "postgres" and not DATABASE_URL:
    raise ValueError("DATABASE_URL is required when STORAGE_BACKEND=postgres")

SUIXINJI_ENV = os.getenv("SUIXINJI_ENV", "dev").strip().lower()
COORDINATION_BACKEND = os.getenv("COORDINATION_BACKEND", "local").strip().lower()
REDIS_URL = os.getenv("REDIS_URL", "").strip()
CACHE_ENABLED = _bool_env("CACHE_ENABLED", True)
AGENT_HOOKS_ENABLED = _bool_env("SUIXINJI_AGENT_HOOKS_ENABLED", True)
TASK_QUEUE_BACKEND = os.getenv("TASK_QUEUE_BACKEND", "local").strip().lower()
FAKE_EXTERNALS = _bool_env("SUIXINJI_FAKE_EXTERNALS", False)
STAGE4_MODE = _bool_env("SUIXINJI_STAGE4_MODE", False)
TEST_API_ENABLED = _bool_env("SUIXINJI_TEST_API_ENABLED", False)
TEST_API_TOKEN = os.getenv("SUIXINJI_TEST_API_TOKEN", "").strip()
TEST_API_DEFAULT_TENANT_ID = os.getenv("SUIXINJI_TEST_API_DEFAULT_TENANT_ID", "default").strip() or "default"
TEST_API_DEFAULT_USER_ID = os.getenv("SUIXINJI_TEST_API_DEFAULT_USER_ID", "").strip()

REDIS_MAX_CONNECTIONS = _int_env("SUIXINJI_REDIS_MAX_CONNECTIONS", 20)
REDIS_SOCKET_TIMEOUT_SECONDS = _float_env("SUIXINJI_REDIS_SOCKET_TIMEOUT_SECONDS", 2.0)
REDIS_CONNECT_TIMEOUT_SECONDS = _float_env("SUIXINJI_REDIS_CONNECT_TIMEOUT_SECONDS", 2.0)
REDIS_HEALTH_CHECK_INTERVAL_SECONDS = _int_env("SUIXINJI_REDIS_HEALTH_CHECK_INTERVAL_SECONDS", 30)

RATE_LIMIT_ASK_PER_MINUTE = _int_env("SUIXINJI_RATE_LIMIT_ASK_PER_MINUTE", 20)
RATE_LIMIT_INGEST_PER_MINUTE = _int_env("SUIXINJI_RATE_LIMIT_INGEST_PER_MINUTE", 120)
LLM_CONCURRENCY_LIMIT = _int_env("SUIXINJI_LLM_CONCURRENCY_LIMIT", 4)
LLM_TOKEN_BUDGET_PER_MINUTE = _int_env("SUIXINJI_LLM_TOKEN_BUDGET_PER_MINUTE", 200000)
IDEMPOTENCY_TTL_SECONDS = _int_env("SUIXINJI_IDEMPOTENCY_TTL_SECONDS", 600)
SESSION_TTL_SECONDS = _int_env("SUIXINJI_SESSION_TTL_SECONDS", 1800)
SPACE_LOCK_TTL_MS = _int_env("SUIXINJI_SPACE_LOCK_TTL_MS", 30000)
SPACE_LOCK_WAIT_SECONDS = _float_env("SUIXINJI_SPACE_LOCK_WAIT_SECONDS", 5.0)
CACHE_SEARCH_TTL_SECONDS = _int_env("SUIXINJI_CACHE_SEARCH_TTL_SECONDS", 180)
EMBEDDING_CACHE_TTL_SECONDS = _int_env("SUIXINJI_EMBEDDING_CACHE_TTL_SECONDS", 86400)
MEMORY_ACCESS_BUFFER_ENABLED = _bool_env("SUIXINJI_MEMORY_ACCESS_BUFFER_ENABLED", True)
MEMORY_ACCESS_FLUSH_BATCH_SIZE = _int_env("SUIXINJI_MEMORY_ACCESS_FLUSH_BATCH_SIZE", 1000)

STREAM_BLOCK_MS = _int_env("SUIXINJI_STREAM_BLOCK_MS", 5000)
STREAM_BATCH_SIZE = _int_env("SUIXINJI_STREAM_BATCH_SIZE", 10)
REDIS_BLOCKING_MAX_CONNECTIONS = _int_env("SUIXINJI_REDIS_BLOCKING_MAX_CONNECTIONS", 8)
REDIS_BLOCKING_SOCKET_TIMEOUT_SECONDS = _float_env(
    "SUIXINJI_REDIS_BLOCKING_SOCKET_TIMEOUT_SECONDS",
    max(7.0, STREAM_BLOCK_MS / 1000 + 1.0),
)
STREAM_CLAIM_IDLE_MS = _int_env("SUIXINJI_STREAM_CLAIM_IDLE_MS", 60000)
STREAM_MAXLEN = _int_env("SUIXINJI_STREAM_MAXLEN", 100000)
OUTBOX_BATCH_SIZE = _int_env("SUIXINJI_OUTBOX_BATCH_SIZE", 50)
OUTBOX_POLL_INTERVAL_SECONDS = _float_env("SUIXINJI_OUTBOX_POLL_INTERVAL_SECONDS", 1.0)
WORKER_MAX_ATTEMPTS = _int_env("SUIXINJI_WORKER_MAX_ATTEMPTS", 5)
WORKER_RETRY_BASE_SECONDS = _float_env("SUIXINJI_WORKER_RETRY_BASE_SECONDS", 2.0)
TASK_LEASE_SECONDS = _int_env("SUIXINJI_TASK_LEASE_SECONDS", 60)
OUTBOX_LEASE_SECONDS = _int_env("SUIXINJI_OUTBOX_LEASE_SECONDS", 30)
OUTBOX_MAX_ATTEMPTS = _int_env("SUIXINJI_OUTBOX_MAX_ATTEMPTS", 10)
STREAM_RECLAIM_INTERVAL_SECONDS = _float_env("SUIXINJI_STREAM_RECLAIM_INTERVAL_SECONDS", 10.0)
SCHEDULER_LEADER_TTL_MS = _int_env("SUIXINJI_SCHEDULER_LEADER_TTL_MS", 30000)

if COORDINATION_BACKEND not in {"local", "redis"}:
    raise ValueError("COORDINATION_BACKEND must be 'local' or 'redis'")
if COORDINATION_BACKEND == "redis" and not REDIS_URL:
    raise ValueError("REDIS_URL is required when COORDINATION_BACKEND=redis")
if TASK_QUEUE_BACKEND not in {"local", "redis_streams"}:
    raise ValueError("TASK_QUEUE_BACKEND must be 'local' or 'redis_streams'")
if TASK_QUEUE_BACKEND == "redis_streams" and (STORAGE_BACKEND != "postgres" or COORDINATION_BACKEND != "redis"):
    raise ValueError("TASK_QUEUE_BACKEND=redis_streams requires PostgreSQL storage and Redis coordination")
if TASK_QUEUE_BACKEND == "redis_streams":
    required_blocking_timeout = STREAM_BLOCK_MS / 1000 + 1.0
    if REDIS_BLOCKING_SOCKET_TIMEOUT_SECONDS < required_blocking_timeout:
        raise ValueError(
            "SUIXINJI_REDIS_BLOCKING_SOCKET_TIMEOUT_SECONDS must be at least "
            "SUIXINJI_STREAM_BLOCK_MS / 1000 + 1 second"
        )
