"""Typed contracts for the V2 Ask workflow."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, field_validator


ASK_INTENTS = (
    "task_state",
    "task_inventory",
    "preference_current",
    "semantic_current",
    "semantic_history",
    "episodic_history",
    "note_lookup",
    "memory_history",
)
ASK_MEMORY_TYPES = ("task", "preference", "semantic", "episodic")
ASK_FACETS = (
    "identity", "location", "education", "career", "project", "learning",
    "capability", "device", "other",
)


class AskContextItem(BaseModel):
    text: str = Field(min_length=1, max_length=500)
    source: Literal["current_message", "session_context"]

    @field_validator("text", mode="before")
    @classmethod
    def clean_text(cls, value: object) -> str:
        return " ".join(str(value or "").split())[:500]


class QueryUnit(BaseModel):
    id: str = Field(min_length=1, max_length=32)
    question: str = Field(min_length=1, max_length=500)
    source_spans: list[str] = Field(default_factory=list, max_length=8)
    intent: Literal[
        "task_state", "task_inventory", "preference_current", "semantic_current",
        "semantic_history", "episodic_history", "note_lookup", "memory_history",
    ]
    memory_type: Literal["task", "preference", "semantic", "episodic"] | None = None
    facet: Literal[
        "identity", "location", "education", "career", "project", "learning",
        "capability", "device", "other",
    ] | None = None
    topic: str | None = Field(default=None, max_length=160)
    time_mode: Literal["current", "recent", "history", "all"] = "all"
    evidence_mode: Literal["current_state", "inventory", "timeline", "source_quote", "aggregate"] = "aggregate"
    need_source_evidence: bool = False
    depends_on: list[str] = Field(default_factory=list, max_length=6)
    priority: int = Field(default=1, ge=1, le=9)

    @field_validator("id", "question", "topic", mode="before")
    @classmethod
    def clean_optional_text(cls, value: object) -> str | None:
        if value is None:
            return None
        return " ".join(str(value).split())

    @field_validator("source_spans", "depends_on", mode="before")
    @classmethod
    def clean_list(cls, value: object) -> list[str]:
        if not isinstance(value, list):
            return []
        return list(dict.fromkeys(
            " ".join(str(item or "").split()) for item in value if str(item or "").strip()
        ))


class AskPlan(BaseModel):
    original_query: str = Field(min_length=1, max_length=2000)
    context: list[AskContextItem] = Field(default_factory=list, max_length=8)
    # The validator trims to the configured runtime limit.  Allow a larger
    # raw model payload here so an over-eager planner can be repaired safely.
    units: list[QueryUnit] = Field(min_length=1, max_length=16)
    answer_mode: Literal["direct", "list", "timeline", "compare", "causal", "summary"] = "direct"


class EvidenceItem(BaseModel):
    evidence_id: str = Field(min_length=1, max_length=128)
    source_kind: Literal["memory", "memory_version", "note"]
    memory_type: Literal["task", "preference", "semantic", "episodic"] | None = None
    content: str = Field(default="", max_length=2400)
    evidence_span: str | None = Field(default=None, max_length=1200)
    # Used only between hydration and deterministic span selection.  It is
    # excluded from model serialization and cleared before the answer LLM sees
    # the bundle, so a selected Note cannot bypass the evidence budget.
    full_text: str | None = Field(default=None, exclude=True)
    fact_hints: list[str] = Field(default_factory=list, max_length=8)
    memory_id: str | None = Field(default=None, max_length=128)
    version_id: str | None = Field(default=None, max_length=128)
    note_id: str | None = Field(default=None, max_length=128)
    source_note_ids: list[str] = Field(default_factory=list, max_length=12)
    event_time: str | None = None
    observed_at: str | None = None
    recorded_at: str | None = None
    # Persisted task-state metadata is evidence, not a conclusion generated by
    # the answer model. It lets timeline answers preserve version order.
    task_status: str | None = Field(default=None, max_length=40)
    retrieval_channels: list[str] = Field(default_factory=list, max_length=8)
    evidence_role: Literal["current_candidate", "historical", "supporting", "conflicting", "raw_note"] = "supporting"


class EvidenceFact(BaseModel):
    """An atomic claim tied to a verbatim span in selected evidence."""

    unit_id: str = Field(min_length=1, max_length=32)
    evidence_id: str = Field(min_length=1, max_length=128)
    quote: str = Field(min_length=3, max_length=600)
    claim: str = Field(min_length=1, max_length=500)
    modality: Literal["asserted", "planned", "uncertain"]
    subject: str | None = Field(default=None, max_length=160)
    predicate: str | None = Field(default=None, max_length=160)
    value: str | None = Field(default=None, max_length=240)
    event_time: str | None = Field(default=None, max_length=80)
    item_key: str | None = Field(default=None, max_length=160)
    quantity: float | None = None


class UnitResolution(BaseModel):
    status: Literal["resolved", "partial", "conflict", "not_found"]
    value: str | None = Field(default=None, max_length=1000)
    reason_code: str = Field(min_length=1, max_length=120)
    selected_evidence_ids: list[str] = Field(default_factory=list, max_length=8)
    conflicting_evidence_ids: list[str] = Field(default_factory=list, max_length=8)


class UnitEvidenceBundle(BaseModel):
    unit_id: str
    evidence: list[EvidenceItem] = Field(default_factory=list, max_length=16)
    facts: list[EvidenceFact] = Field(default_factory=list, max_length=12)
    fact_summary: str | None = Field(default=None, max_length=1000)
    resolution: UnitResolution


class AskWorkflowResult(BaseModel):
    answer: str
    answer_source: str
    answer_type: Literal["answered", "no_answer", "qualified_history_only", "conflict", "clarification", "restricted"] = "answered"
    reason_code: str = "evidence_supported"
    plan: AskPlan
    bundles: list[UnitEvidenceBundle]
    selected_records: list[dict] = Field(default_factory=list)
    observations: list[dict] = Field(default_factory=list)
    # The UI may render only `answer`; integrations can audit this support
    # without reverse-parsing prose.
    claims: list[dict] = Field(default_factory=list)
    claim_groups: list[dict] = Field(default_factory=list)
